# -*- coding: utf-8 -*-
"""CS771_2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CJrokHI5tjP5HWQiGZU92uXqrsa_6mBa
"""

from email import utils
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import normalize
import pickle
from utils import *

filename = 'train'
X,y = loadData( filename, dictSize = 225 )
normalize(X,axis=0)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)

model = LogisticRegression(solver="newton-cg",max_iter=150,multi_class='multinomial',C=11)
clf = OneVsRestClassifier(model)   
clf.fit(X, y)

probs = clf.predict_proba(X_test)
best_5 = np.argsort(probs, axis=1)[:,-5:]
best_5_classes = clf.classes_[np.fliplr(best_5)]


model_name = "CS771_2.pkl"
with open(model_name, 'wb') as file:
  pickle.dump(clf,file)